name: Would you like to see a feature implemented?
description: Request a new feature for Winston
title: "[Feature Request]: "
labels: ["Feature", "Needs Investigation"]
body:
  - type: markdown # Form Header
    attributes:
      value: |
        This issue form is for requesting features only! Please help us reduce duplicate issues by searching through both
        open and closed issues though. It only takes 5 minutes and helps us with housekeeping. :)
  - type: textarea # Feature Definition
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Please provide a clear and concise description of the feature you would like to see implemented.
  - type: markdown # Feature Details Section
    attributes:
      value: |
        # Details
  - type: textarea # Use Case Input
    attributes:
      label: Use case
      description: |
        If you desire you can provide use cases for the requested feature.
      render: yaml
  - type: textarea # Additional Information
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us that you feel will be valuable, please use the field below.
